[project]
version = "0.1.0"
name = "json"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[dependencies]
err  = "1"
pool = "1"
map  = "1"
vec  = "1"
hex  = "1"
ast  = "1"
byteorder = "1"

[variants]
default = []
