name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Artifact
      run: |
        7z a artifact.zip modules/

    - name: macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install SRI-CSL/sri-csl/yices2
        ./ci.sh

    - name: ubuntu
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo add-apt-repository ppa:sri-csl/formal-methods
        sudo apt-get update
        sudo apt-get install yices2
        ./ci.sh

    - name: windows
      if: matrix.os == 'windows-latest'
      run: |
        curl -fsSL "https://yices.csl.sri.com/releases/2.6.2/yices-2.6.2-x86_64-pc-mingw32-static-gmp.zip" -o "yices2.zip"
        7z e "yices2.zip" -o/c/z3_downloaded -r -y
        rm -rf /c/z3_downloaded/z3 ## this is an empty directory
        export "PATH=/c/z3_downloaded:/c/msys64/mingw64/bin/:$PATH"
        clang --version
        export "ZZ_ASAN=false"
        ./ci.sh

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/master'
      env:
       FILE: ./.zip
       AWS_REGION: 'eu-west-1'
       S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       GITHUB_OS: ${{matrix.os}}
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

        7z a artifact.zip target/release/zz*
        export BNAME="zz-${GITHUB_RUN_NUMBER}-${GITHUB_SHA}-$(echo $GITHUB_OS | cut -d '-' -f 1).zip"
        aws s3 cp artifact.zip s3://${S3_BUCKET}/${BNAME} --region ${AWS_REGION} --acl public-read
        export BNAME="zz-master-$(echo $GITHUB_OS | cut -d '-' -f 1).zip"
        aws s3 cp artifact.zip s3://${S3_BUCKET}/${BNAME} --region ${AWS_REGION} --acl public-read



